name:                dynamic-array
version:             0.1.2.0
license:             MIT
author:              "Andr치s Kov치cs"
maintainer:          "puttamalac@gmail.com"
copyright:           "2018-2021 Andr치s Kov치cs"

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-name-shadowing
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-partial-type-signatures
  - -O2
  - -fllvm

library:
  source-dirs: .
  dependencies:
    - base >= 4.7 && < 5
    - primdata
