resolver: lts-19.21

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 644230c40c11ff10f04dbd9b00256c6691972594

ghc-options:
    "$everything": -split-sections
