resolver: nightly-2021-09-18

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: a6b05e301f60f66a65497ec2105176c1f22b4317

ghc-options:
    "$everything": -split-sections
