resolver: nightly-2021-09-18

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 72e76bad5291fb5392c5c63c11f0d44dfbec904a

ghc-options:
    "$everything": -split-sections
