resolver: lts-16.31

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: d050c16a088e973de879941aafb2c07c319a7a31

ghc-options:
    "$everything": -split-sections
