resolver: nightly-2023-02-09

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 46b257c41a9eb0ad99ac1cd8c5dda029601089f5

ghc-options:
    "$everything": -split-sections
