resolver: nightly-2023-10-24

packages:
- .

extra-deps:
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 488d38201d0845a0e4e9e80ce78126ebae77350f

ghc-options:
    "$everything": -split-sections
